version: '3.8'

services:
  backend:
    build: 
      context: backend
      dockerfile: DockerFile
    ports:
      - "5000:5000"
    command: flask run

  frontend:
    build: 
      context: frontend
      dockerfile: DockerFile
    ports:
      - "80:80"

